version: '3.3'
services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    volumes:
      - $UPTIME_KUMA_VOLUME:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 3001:3001  # <Host Port>:<Container Port>
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"

